# Automatically generated tests for validation using CSV data
import pytest
import dataclasses
import datetime
import typing
from source_files.validation import equal

# This file was generated by the test_case_generator with CSV data

# Tests for function equal
@pytest.mark.parametrize('inputs,expected', [
    # CSV-defined test for equal
    ([5, 5], 'true'),
    # CSV-defined test for equal
    ([10, 5], 'false'),
    # CSV-defined test for equal
    ([0, 0], 'true'),
    # CSV-defined test for equal
    ([-5, -5], 'true'),
    # CSV-defined test for equal
    ([-5, 5], 'false'),
    # CSV-defined test for equal
    ([100, 100], 'true'),
    # CSV-defined test for equal
    ([0, 1], 'false'),
    # CSV-defined test for equal
    ([-10, -10], 'true'),
])
def test_equal(inputs, expected):
    assert equal(*inputs) == expected
