# Automatically generated tests for demo
import pytest
import dataclasses
import datetime
import typing
from source_files.demo import demo

# This file was generated by the test_case_generator

# Tests for function demo
@pytest.mark.parametrize('inputs,expected', [
    # Edge case for a=0
    ([0, 417], -417),
    # Edge case for a=1
    ([1, -206], -205),
    # Edge case for a=-1
    ([-1, 547], -548),
    # Edge case for a=100
    ([100, 969], -869),
    # Edge case for a=-100
    ([-100, 655], -755),
    # Edge case for b=0
    ([283, 0], 283),
    # Edge case for b=1
    ([22, 1], 23),
    # Edge case for b=-1
    ([-811, -1], -810),
    # Edge case for b=100
    ([263, 100], 363),
    # Edge case for b=-100
    ([-803, -100], -703),
    # Test with inputs: [-344, -557]
    ([-344, -557], -901),
    # Test with inputs: [960, -272]
    ([960, -272], 688),
    # Test with inputs: [271, -621]
    ([271, -621], -350),
    # Test with inputs: [-149, 738]
    ([-149, 738], -887),
    # Test with inputs: [117, -595]
    ([117, -595], -478),
])
def test_demo(inputs, expected):
    assert demo(*inputs) == expected
